### ISSUE TITLE
Support Linux?

### ISSUE THREAD

**Issue by YeungKC** [ryanheise/just_audio#332]
**Is your feature request related to a problem? Please describe.**
At the moment it looks like support for window is in progress, if Linux can also be supported then great~~

**Describe the solution you'd like**
n.a

**Describe alternatives you've considered**
n.a

**Additional context**
n.a

**Comment by maks** [comment]
Tying this to the [windows support issue](https://github.com/ryanheise/just_audio/issues/103#issuecomment-800961589) is where the dart_vlc plugin from @alexmercerind has been discussed to support windows and it now has suport for linux too.

**Comment by ryanheise** [comment]
Since I personally use Linux, I may personally give this a try (no ETA, though, since I'm also working on several other issues - if someone wants to jump in before me, advertise your intent both here and on the windows support issue so that we don't duplicate effort.)

**Comment by GZGavinZhao** [comment]
I'm thinking about using [ALSA ](https://alsa-project.org/wiki/Main_Page) library with FFI to support audio on Linux.

**Comment by maks** [comment]
@GZGavinZhao no need to think about it, I've got a [package already with simple playback working](https://pub.dev/packages/dart_alsa), PR contributions most welcome. Sorry @ryanheise I forgot to report back here when I started working on it.

If you'd like something more cross-platform, I can recommend the [libao package](https://pub.dev/packages/libao) which I've been happily using recently.

**Comment by GZGavinZhao** [comment]
@maks That's awesome! I have thought about `libao` before, but I think it would be better if we either just stick to separate frameworks for each platform or use a unified cross-platform framework, otherwise things might get messy. Since those who have been working on the Windows and Mac OS compatibility seem to already found their choice (correct me if I'm wrong), `alsa` might be the most suitable one for now.

Also, I'm a little bit worried about `libao`'s support because it has been pretty long since they've had a new release.

**Comment by ryanheise** [comment]
Options options options!

There is no problem having multiple implementations in a federated plugin framework.

In #103 we had come up with a naming convention like this:

```
just_audio_library_platform
```

For example:

```
just_audio_libao_macos
just_audio_libao_windows
just_audio_libao_common
```

From the libao page it looks like there are multiple targets for linux, but we could still fit them into the above naming framework by treating `oss`, `pulse` and `alsa` as different platform targets (unless anyone has other suggestions?)

**Comment by maks** [comment]
My requirements for are for realtime audio synthesis, sample-playback and filter application (delay, reveb, etc) which I think are very different from just_audio's focus on media file/stream playback, compressed format support, metadata management etc, so I'm using Alsa and Libao directly via my packages, but like I said I'm happy to accept PRs that add whatever functionality would be needed to for it to be used by this package for linux support. But again given the rich feature set that just_audio already supports, I think you may find that using something like [MiniAudio](https://miniaud.io/) would work better, given its support of many of those features, even if you don't need it's multiplatform support, even though on Linux Pulseaudio is now the most widely used audio server, direct Alsa use is much less common and Jack is widely used for music-production low-latency applications.

**Comment by maks** [comment]
@ryanheise  yes that naming sounds good, let a thousand flowers (platform implementations) bloom! 🙂  👍🏻

**Comment by GZGavinZhao** [comment]
Was able to get `miniaudio` to work under linux with `dart:ffi`, though I still need to try out how to asynchronously call the methods. `miniaudio` itself claims that it's asynchronous, so I guess there are some problems I need to figure out on the Dart side.

**Comment by alexmercerind** [comment]
@GZGavinZhao that's cool, but what's easiest is to map [dart_vlc](https://github.com/alexmercerind/dart_vlc) to just_audio's platform channel interface.

You guys don't need to worry about playback backends (or anything native), dart_vlc is being maintained by me & a lot of time has been already spent making it stable & fixing issues reported by the users. dart_vlc is also part of awesome-vlc page from one of libVLC community members [here](https://github.com/mfkl/awesome-vlc#bindings).

You can just add dart_vlc as a dependency to just_audio & use it. I'm also using FFI in this project now (earlier it was based on platform channels, until that time I couldn't figure out async callbacks). Just using FFI wasn't enough, I have also added event callbacks for position, video frames etc. through NativePorts of Dart VM. You just need to add Dart mapping to dart_vlc for just_audio.

If you are not statisfied with dart_vlc's interface, you can use baremetal dart_vlc_ffi package that dart_vlc internally uses. It also has callbacks support.

Speaking of miniaudio, alsa or libao... Those libraries are really really low level, even writing network streaming from scratch will give us a lot of pain. libVLC already offers a nice interface & dart_vlc brings its most features to Dart.
Audio playback is one of the features that we're offering & you can use it in just_audio.

@megamegax spent bit of time earlier trying this. But hasn't done much after that. https://github.com/megamegax/just_audio

And, let me know in the issues of dart_vlc if you guys face any kind of problem or issue. I'll be fixing them as best as I can.

Thanks.

**Comment by alexmercerind** [comment]
For Windows, I have even better idea to use C++/winRT APIs themselves in future. Why deal with libao, libao buffers, decoding & all... (So, I'm working on an another separate side side side project to expose those APIs in a DLL, so that Dart VM can use it).
It is going to be very light (while still having a lot lot better media codec support & features compared to miniaudio) since there will be no third party library used for playback but core Windows APIs. But, for now dart_vlc will be cool.

miniaudio is like a dead-end at this point unless one is really really geek to build things like network streaming, better format support on top of it. Speaking of miniaudio, I already worked on it (possibly world's first) to play audio on Flutter desktop, [flutter_audio_desktop](https://github.com/alexmercerind/flutter_audio_desktop), but dart_vlc is just better.

**Comment by GZGavinZhao** [comment]
@alexmercerind Wow thanks for the suggestions and resources! I'm checking it out now. One concern I do have is about external dependencies (which was why I first tried `miniaudio`). When using `dart_vlc`, do we need any dependencies on the client side? I know that for developers we need the vlc development libraries, but when we build a Flutter app and distribute it to the users, do  the users need to install anything on their side (perhaps something like `libvlc`)?

**Comment by alexmercerind** [comment]
@GZGavinZhao on Windows, I provide the libvlc source directly within the plugin & all the shared libraries are automatically copied with CMake (I have everything ready already, don't worry about that). 

On debian, one must have libvlc & libvlc-dev installed with apt (I believe depending on distro's repos is best bet). Someone has also added info to build it on redhat based distros. Not sure about arch however (although people have built it successfully on manjaro).

I have written everything in the README that you might need to know about it.

**Comment by GZGavinZhao** [comment]
@alexmercerind Understood. Thanks for the detailed explanation!

**Comment by maks** [comment]
@GZGavinZhao great work getting miniaudio working, do you have a repo with that FFI binding? I started doing a package for FFI binding but didn't get very far before switching to Alsa and then libao.

I'm not sure why @alexmercerind you said "FFI isn't enough"? You just need to call sync C APIs like libao in a isolate to ensure you don't block the main isolate. I've done a simple implementation of that recently for my project and I'll write up an article on how to do that soon.

And yes with respect to libvlc you *will* need to ship it as a shared lib in your Flutter app to your users and be aware that while libvlc is LGPL licenced some modules maybe be GPL so that would mean your app then needs to be GPL too.

It's all really dependent on what you need. I chose to use Alsa and libao (miniaudio on my to-do list too) as I do need low level, sample level API access. If you instead only want a higher level API with features like streaming or compressed formats then something like libvlc is probably better choice which it might be given that just _audio seems to be more focused on those use cases.

**Comment by alexmercerind** [comment]
@maks 
> I'm not sure why @alexmercerind you said "FFI isn't enough"? You just need to call sync C APIs like libao in a isolate to ensure you don't block the main isolate. I've done a simple implementation of that recently for my project and I'll write up an article on how to do that soon.

Yes, FFI is not enough unless they fix this: https://dartbug.com/37022.

Its not about sending messages to C/C++ from Dart, but its also about being able to receive messages from Dart. miniaudio in comparison to libvlc or winRT APIs is very basic, there isn't much like event callbacks.

In just_audio, there are many event streams (as Dart has those great things) e.g. for position, playlist & other events etc. etc. (github.com/ryanheise/just_audio/blob/e312da2a210ac7b5c0c4ba85cc59c2c832cff52b/just_audio/lib/just_audio.dart#L301-L404)
FFI is enough, if you just need to talk from Dart to C/C++, but not the other way around.
And I'm not sure how will you be able to feed any Stream<T> with values being returned from C/C++ asynchronously. Its a bug in FFI itself.

See how I had to use NativePorts to send back position, video frame buffers, playlist events etc. etc. asynchronously. https://github.com/alexmercerind/dart_vlc/blob/master/ffi/native/eventmanager.hpp because FFI wasn't enough.

Now one might say why use Stream or async callbacks, just leave it... Because that's how a Dart library is made, all developers are familiar with Stream subscriptions & its the easiest way to update the UI. Thus, for notifying about events being happened asynchronously, its necessary to send updates back to Dart. More on what problem is here in this comment: https://github.com/ryanheise/just_audio/issues/103#issuecomment-798848254. In C++/winRT aswell, one can register for event callback by passing a lambda, but using that in FFI will certainly result in a crash or use NativePorts.

> And yes with respect to libvlc you will need to ship it as a shared lib in your Flutter app to your users and be aware that while libVLC is LGPL licenced some modules maybe be GPL so that would mean your app then needs to be GPL too.

libVLC can be compiled with only LGPL modules enabled. And difference will be unnoticeable. If one doesn't even wanna compile, they can just delete the shared libraries.

> It's all really dependent on what you need. I chose to use Alsa and libao (miniaudio on my to-do list too) as I do need low level, sample level API access. If you instead only want a higher level API with features like streaming or compressed formats then something like libvlc is probably better choice which it might be given that just _audio seems to be more focused on those use cases.

That's what I also believe. For just_audio, general high-level interface to audio playback is required with features like network streaming, good format support, event callbacks etc. and its just hard to do in miniaudio or from bare alsa/libao & if one decides to do it themselves (it might be another media player from scratch...), it will be far from just a "binding" or a "plugin".

**Comment by maks** [comment]
@alexmercerind 
> Its not about sending messages to C/C++ from Dart,
Thats correct, because we are talking about FFI not platform channels, so we are not sending any messages, instead with FFI we are making function calls.

I don't know what API libvlc exposes, but Alsa and libao have synchronous APIs so theres no need for async callbacks from native code into Dart. 

As I said you simply need to use a seperate Isolate that then exposes an event stream to ihe main Isolate. You don't give up on using Streams, you simply use standard Send/Recieve ports that Dart provides for all interisolate comms. The main isolate can then expose whatever streams are required using messages coming in from second isolates receive port. [Here is a gist](https://gist.github.com/maks/7b8685e1f3910b75c9574ba38f8da603) with code extracted from one of my recent projects that demonstrates the basic of this approach. My code is using sample based playback with libao, so its trivial to have this code report a playback stream in the main Isolate.

**Comment by GZGavinZhao** [comment]
@maks Thanks! I wouldn't call it a proper binding though, because technically I didn't wrap the `miniaudio.h`; I only bound the example [here](http://miniaud.io/docs/examples/simple_playback.html) to Dart.

@ryanheise Just found a problem: because `just_audio` depends on `audio_session`, which doesn't have a Linux implementation, implementing `just_audio` for Linux would also mean implementing `audio_session` for Linux. Any work-around for that?

**Comment by maks** [comment]
@GZGavinZhao a vaguely remember that audio session type functionality is available via DBus on Ubuntu and many other distros and there is already a DBus package available written by one of the Ubuntu staff developers.

**Comment by ryanheise** [comment]
Hmm, I thought I had already implemented audio_session as a noop on other platforms. That is something I should fix:

https://github.com/ryanheise/audio_session/issues/34

**Comment by ryanheise** [comment]
OK, this is now implemented in the git version of audio_session but I'll hold off doing a release until we can test whether this solves the issue.

**Comment by ryanheise** [comment]
Hi @megamegax I was just taking a look at your code and it looks like quite a clever approach! Basically, to start with the existing web implementation as a base, since it already implements all of the backend logic, and then just substitute in the vlc player instead of the HTML5 audio element.

Of course eventually we could reimplement the backend logic using vlc features like playlist, although that could be a substantial amount of work.

Are you interested in continuing on your project and/or collaborating? Or would it be best to work on it as a sub-project of the main just_audio repo? The idea of the federated plugin model is that in theory anyone can create an independent platform implementation and publish it themselves on pub.dev without my needing to be involved, but if it helps to get this thing off the ground, I don't mind having a more central effort.

By the way, if you are willing to keep working on it, I'd suggest opening up the GitHub issues page to invite collaborators to help submit bugs, etc. as well as get the license and copyright notice in place. Then I could also link from my project to your page and give it more attention. Either way is workable to me.

**Comment by GZGavinZhao** [comment]
@ryanheise Thanks for the quick help! Progress is unfortunately blocked because of this [issue](https://github.com/flutter/flutter/issues/52267), which basically says that there's no way of to creating a Dart implementation of a platform interface except for web. The problem is that if we use `dart_vlc`, we'll be definitely writing Dart code (and perhaps pure Dart code).

They did provide one way to manually force the use of pure Dart plugins (as shown in this line [here](https://github.com/flutter/plugins/blob/fc6bd9834c7881d076086abaa7b74c9d317fb2bc/packages/path_provider/path_provider/lib/path_provider.dart#L34) taken from the first-party plugin `path_provider`). If we choose this work-around, our implementation will essentially become endorsed, which I'm not sure if this is something we want???

**Comment by ryanheise** [comment]
@GZGavinZhao Yes, I was coincidentally looking at path_provider last night for the same reason. So in the VLC case, something like this is now possible:

```yaml
flutter:
  plugin:
    implements: just_audio
    platforms:
      linux:
        dartPluginClass: JustAudioVlcPlugin
        pluginClass: none
```

And then inside the Dart file we can have:

```dart
class JustAudioVlcPlugin extends JustAudioPlatform {
  final Map<String, JustAudioVlcPlayer> players = {};

  /// The entrypoint called by the generated plugin registrant.
  static void registerWith() {
    JustAudioPlatform.instance = JustAudioVlcPlugin();
  }

  ...
}
```

But no it won't become endorsed unless the main frontend plugin's pubspec file declares it so. Platform implementions can't endorse themselves.

By the way, it is still technically possible to get a Dart platform implementation working without the above feature, as I have used a workaround in `just_audio_background` where the app needs to manually invoke a static method to do the registration. In just_audio_background it makes sense because there are parameters we want to pass into init anyway.

**Comment by GZGavinZhao** [comment]
@ryanheise I tried to use this approach with the pubspec file but it didn't work. :( 
Here's what I currently [have](https://github.com/GZGavinZhao/just_audio_vlc_linux).

In case you're wondering, the reason I added an extra "linux" after the plugin name and class is because I want to call some native code to do native volume controls and notifications, and this can help differentiate from the Windows implementation.

**Comment by ryanheise** [comment]
Just a quick comment, on the plugin name, but if the plugin is written entirely in Dart and you move all of the native code into a separate dependency, and if consequently the Windows and Linux Dart implementations are largely the same, you can also just write if/else statements depending on the platform.

**Comment by ryanheise** [comment]
> @ryanheise I tried to use this approach with the pubspec file but it didn't work. :(

I just tried the path_provider example on linux and it works. I then tried un-endorsing the linux implementation and manually added it as a dependency to the example, and it still worked.

It's still a mystery to me what could be the difference between that and your project, but maybe it's a starting point for investigation?

**Comment by GZGavinZhao** [comment]
@ryanheise I'm gonna try this again tomorrow, but just to confirm, what branch/version of Flutter are you on?

**Comment by ryanheise** [comment]
I'm on stable. 2.2.2. (I've been prompted to upgrade, but I expect if this version works, newer versions will also work.)

**Comment by alexmercerind** [comment]
@ryanheise 
> Just a quick comment, on the plugin name, but if the plugin is written entirely in Dart and you move all of the native code into a separate dependency, and if consequently the Windows and Linux Dart implementations are largely the same, you can also just write if/else statements depending on the platform.

A package would be most likely what you must use. And use `just_audio_vlc_linux` as a dependency package.

And, you can keep same package for both Windows & Linux (and remove `_linux`), since those two are the platforms that I'm supporting in my plugin.

**Comment by GZGavinZhao** [comment]
@ryanheise For `path_provider`, they manually forced the use of their Linux implementation when the platform detected is Linux. See [this line](https://github.com/flutter/plugins/blob/a3accd7c2fc72150c225a919d336819066759620/packages/path_provider/path_provider/lib/path_provider.dart#L51). So I believe for now, unless you manually put something similar [here](https://github.com/ryanheise/just_audio/blob/8451d2e041da4763941827f51800e70454dac729/just_audio/lib/just_audio.dart#L1250), like an `if-else` or a `switch` statement, we're unable to do a pure Dart Linux implementation :(

**Comment by GZGavinZhao** [comment]
@ryanheise  Okay I think my idea was on the right track. This was the [manual override](https://github.com/GZGavinZhao/just_audio/commit/b524c2eca0d0e02d2a07d14025932e4263eeea2b) I was talking about, and the implementation will work after this.

@alexmercerind One little problem here: for a player's id, `just_audio` uses uuid while `dart_vlc` uses int... Will it be a big problem for you to change that? I can also try to crunch it into a pointer (uuid is 128 bits and an unsigned Dart int is 64 bit).

**Comment by ryanheise** [comment]
For now, I would go for the solution used in just_audio_background so that the front-end plugin doesn't hard-code anything. What that involves is just exposing some static method that will install the platform implementation, and then any app that wants to use the Linux implementation should then manually call it in their main method:

```dart
if (!kIsWeb && Platform.isLinux) {
  JustAudioVlcPlugin.install();
}
```

Or alternatively you could expose a static method that does the conditional code itself:

```dart
void register() {
  if (!kIsWeb && Platform.isLinux) {
    _platform = JustAudioVlcPlugin();
  }
}
```

And from the app's main method call:

```dart
  JustAudioVlcPlugin.register();
```

This is similarly a temporary solution but it would just be a way of allowing multiple Linux implementations to exist.

**Comment by ryanheise** [comment]
> @alexmercerind One little problem here: for a player's id, `just_audio` uses uuid while `dart_vlc` uses int... Will it be a big problem for you to change that? I can also try to crunch the uuid into a pointer (uuid is 128 bits and an unsigned Dart int is 64 bit).

Why can't you create a hash table that maps one ID onto the other?

**Comment by alexmercerind** [comment]
> @alexmercerind One little problem here: for a player's id, just_audio uses uuid while dart_vlc uses int... Will it be a big problem for you to change that? I can also try to crunch the uuid into a pointer (uuid is 128 bits and an unsigned Dart int is 64 bit).

This infact is one of the reasons I assume that is bringing kinda confusion to everyone. I will try to add support for both `int` & `String` id for `Player` (from Dart itself). I didn't wanna use `String` as "identifier" because strings aren't a primitive data type in C & transferring them or any arrays through FFI is just bit of a work & I decided to avoid it as much as I could.

I believe going with what Ryan said would be great, possibly assign the `id` as the hash table's size for each new instance of `Player`. it will kinda work like an index.

**Comment by ryanheise** [comment]
Just FYI I have published a new audio_session which includes the no-ops for Linux and Windows.

**Comment by ryanheise** [comment]
Hi all. @bdlukaa has just published a [just_audio_libwinmedia](https://pub.dev/packages/just_audio_libwinmedia) based on libwinmedia which adds Windows and Linux support to just_audio. The just_audio example directory has been updated to demonstrate how to use this, although it is currently untested for Linux. I was running into FFI issues when trying to build for Arch Linux, but YMMV. Please let me know below if anyone is able to get it working on their Linux distribution and we can try to improve the setup instructions.

**Comment by maks** [comment]
That looks very interesting, looking forward to trying it out on Linux. 

Looks like the approach libwinmedia takes (at least on Linux) is to wrap the gtk webview to provide the play back functionality, certainly an interesting approach! I don't see that dependency documented in the libwinmedia readme so @ryanheise maybe that's what's causing your FFI issues?

**Comment by ryanheise** [comment]
I did have to manually install the shared lib dependencies, but even still I was getting a freeze without any actual error message. For me the freeze happens at the FFI call, and this never reaches the native plugin code. I've created an issue for libwinmedia here: https://github.com/harmonoid/libwinmedia/issues/6 .

**Comment by Sotneo** [comment]
@ryanheise @bdlukaa @alexmercerind  I was able to run just_audio example without freezes under Linux after slightly patching libwinmedia(typo, merged) and example code(preload: false). Looks like something wrong with preloading. 
```
      await _player.setAudioSource(
          AudioSource.uri(Uri.parse(
              "http://10.217.251.154/calls/1516715759.19611-2018-01-23-17_55-109-89297076020.mp3")),
          preload: false);
```

**Comment by bdlukaa** [comment]
Here is a list of features that are supported in comparison to windows:

| Feature                        | Windows | Linux |
| ------------------------------ | :-----: | :---: |
| read from URL                  |   ✅    |  ✅   |
| read from file                 |   ✅    |  ✅   |
| read from asset                |   ✅    |  ✅   |
| read from byte stream          |         |       |
| request headers                |         |       |
| DASH                           |   ✅    |       |
| HLS                            |   ✅    |       |
| ICY metadata                   |         |       |
| buffer status/position         |   ✅    |       |
| play/pause/seek                |   ✅    |  ✅   |
| set volume/speed               |   ✅    |  ✅   |
| clip audio                     |         |       |
| playlists                      |   ✅    |  ✅   |
| looping/shuffling              |   ✅    |       |
| compose audio                  |         |       |
| gapless playback               |   ✅    |       |
| report player errors           |         |       |
| handle phonecall interruptions |         |       |
| buffering/loading options      |         |       |
| set pitch                      |         |       |
| skip silence                   |         |       |
| equalizer                      |         |       |
| volume boost                   |         |       |

**Comment by ryanheise** [comment]
> @ryanheise @bdlukaa @alexmercerind I was able to run just_audio example without freezes under Linux after slightly patching libwinmedia(typo, merged) and example code(preload: false). Looks like something wrong with preloading.
> 
> ```
>       await _player.setAudioSource(
>           AudioSource.uri(Uri.parse(
>               "http://10.217.251.154/calls/1516715759.19611-2018-01-23-17_55-109-89297076020.mp3")),
>           preload: false);
> ```

Interesting. The preload parameter is actually handled completely in the Dart layer, and setting it to `false` basically delays the inevitable method call to the platform implementation to load the audio. Since the same load method is called in both cases, the only difference is "when" it is called. I would guess this is some sort of timing issue.

**Comment by bdlukaa** [comment]
It's probably because a webview is used in Linux, and it's loaded asynchronously.

**Comment by alexmercerind** [comment]
I implemented another bunch of missing features for Linux (I believe it is now same as Windows):

```
* PlayerAdd
* PlayerIsLooping
* PlayerIsAutoRepeat
* PlayerIsShuffling
* PlayerSetDownloadProgressEventHandler
* PlayerSetErrorEventHandler
* respective getters.
```
Crash was already resolved by @Sotneo the other day.
I ask to give it another try.

<img src='https://user-images.githubusercontent.com/28951144/135826269-f79bf291-34e6-4a43-a874-efe84c19eab8.jpg' height='400'></img>

**Comment by alexmercerind** [comment]
> That looks very interesting, looking forward to trying it out on Linux.
> Looks like the approach libwinmedia takes (at least on Linux) is to wrap the gtk webview to provide the play back functionality, certainly an interesting approach! 

I'm glad to hear. :smile: 
I just decided to just wrap GTK WebKit webview, because `GStreamer`'s pipeline based APIs were just wild. Other stuff like `portaudio`, `ALSA`, `miniaudio` were just too low level (I don't wanna implement network streaming from scratch) for the purpose, others were very strict licensed. This is providing a good set of features, APIs & good format support aswell (atleast all my music is playing). In case one wants more, they can just install `gstreamer` plugins from the distro package manager.
Just only problem that took a lot of time to deal with was GTK being single threaded & web-view interop.

**Comment by ryanheise** [comment]
Awesome! Thanks, @Sotneo and @alexmercerind . It seems to be working well so far on my Linux box.

**Comment by Sotneo** [comment]
> Awesome! Thanks, @Sotneo and @alexmercerind . It seems to be working well so far on my Linux box.

I am still experiencing freezes with examples. Some async staff inside  _init() hangs the process.
If I add some delay via `await Future.delayed(const Duration(microseconds: 1));`. All examples are working.

**Comment by bdlukaa** [comment]
Hello everyone! I will publish the new version of just_audio_libwinmedia with libwinmedia updated

**Comment by nathanfranke** [comment]
https://github.com/ryanheise/just_audio/issues/582

**Comment by ryanheise** [comment]
@nathanfranke can you elaborate?

**Comment by esiqveland** [comment]
Maybe this could serve as inspiration for GStreamer based implementation on linux for just_audio? https://github.com/bluefireteam/audioplayers/pull/1110

**Comment by ryanheise** [comment]
Just tagging @UnicornsOnLSD into the conversation, who was contemplating a GStreamer implementation in #103 :

> For Linux, I've wanted to make a GStreamer package for a while but never got around to it, and I doubt it could be endorsed due to GStreamer's LGPL license (unless it doesn't really count since you wouldn't statically compile GStreamer?)

Also tagging @bleonard252 into the conversation who has just published a Linux implementation based on MPV! link below:

https://pub.dev/packages/just_audio_mpv (Also see issue #725 ).

**Comment by UnicornsOnLSD** [comment]
I'll have a look at that audioplayers implementation if I decide to make one for just_audio, although I may not now that an mpv implementation exists since mpv is awesome and it looks like it implements everything I need. A GStreamer implementation may be easier to port to iOS/Android (one reason I was going to do a GStreamer impl was because of lack of Opus on iOS).

**Comment by bleonard252** [comment]
The key downside to mpv as it is is that it has to already be installed. I could bundle mpv builds with the plugin but that would end up making the bundle size bigger, and it would be harder to reproduce the builds.

I do know mpv supports Android but I'm not sure about iOS.

**Comment by UnicornsOnLSD** [comment]
On Linux mpv could be made a dependency if the program is being distributed as a package, or it could be included in a Flatpak/Appimage. Only downside I can think of is that with traditional packages the user may notice mpv being installed.

**Comment by KRTirtho** [comment]
I made mpv_dart but I didn't sug

>

**Comment by KRTirtho** [comment]
I made mpv_dart but didn't suggest as its suffering from the same reason libwinmedia is suffering. Bundle heaviness & no embeding support
I'm working on a project, an audio player made with rust's clap & symphonia using flutter_rust_bridge & gRPC + protocol buffer
The player is ready (local files only currently) & now I only have to bind with flutter/dart using gRPC & protobuf for basic playback
https://github.com/KRTirtho/rowdy

**Comment by bleonard252** [comment]
For the record: just_audio_mpv should not be endorsed, but rather serve as a solution that can work while other solutions, like Rowdy, GStreamer, and/or ALSA are being worked on.

I look forward to that Rowdy by the way. ~~Maybe it won't be just a port of the node.js implementation this time~~

May 16, 2022 06:11:04 Kingkor Roy Tirtho ***@***.***>:

**Comment by KRTirtho** [comment]
@bleonard252 Great work btw. Yeah, definitely mpv is a much better solution than webkit2gtk in my opinion. A lot lighter, less resource heavy & has awesome + fun APIs to manipulate audio
I will keep working on rowdy to make it a viable solution but till then just_audio_mpv is a better replacement. Contributions to rowdy are much appreciated

**Comment by KRTirtho** [comment]
[Rowdy](https://github.com/KRTirtho/rowdy/tree/impl-rustee-rowdy) now supports following:
- Local Audio file
- Formats: mp3, flac, wav & ogg. (acc is supported but the decoder is failing for some reason)
- Play, Pause/Resume, Toggle Playback, Stop
- Volume (in percentage)
- Speed

**Comment by ryanheise** [comment]
Nice work! I will update the README to link to these.

Just a note on the feature sets, reading from a byte stream, and request headers, should (I would expect) be supported for free because they are handled by the plugin's front-end by setting up a proxy, and then passing the proxy URL to the platform implementation. As long as the platform implementation handles URLs, then it will (or should) implicitly support these other two features.

There is a similar situation where if the platform supports loading audio from a local file, you will also get the ability to play from assets for free.

**Comment by ryanheise** [comment]
@bleonard252 I am about to publish an updated README pointing to your just_audio_mpv plugin. I was thinking it might be helpful if you also update your README to contain installation instructions, specifically about installing the `mpv` dependency (and maybe anything else needed in the tool chain). Of course the instructions would vary for different distributions but I think it might be OK to just include instructions for one of the more popular distributions and then comment generically that users of other distributions can look for the equivalent `mpv` package in their own package manager and install that.

**Comment by bleonard252** [comment]
I'm about to go to sleep but I'll do that in the morning.

**Comment by KRTirtho** [comment]
mpv is already available in debian & ubuntu repositories & of course The AUR has it already. Both flatpak & snap also have it available in their repos
The only problem is I guess fedora & rpmfusion

**Comment by bleonard252** [comment]
the `just_audio_mpv` readme has been updated (although I pushed the Fedora instructions AFTER I pushed it to pub...)

**Comment by ryanheise** [comment]
:+1: looks good. I think that link to the MPV installation page covers all bases. I forgot this is actually a Linux _and_ Windows implementation, but I suppose that is similarly handled by that link to the MPV installation page?

**Comment by UnicornsOnLSD** [comment]
Just wondering, why does it say to get `mpv-git`? `mpv` is in the official repos

**Comment by KRTirtho** [comment]
@ryanheise Well, MPV works on Windows/MacOS too but the `mpv_dart` doesn't support Windows yet & only works in *nix based OSs including (Mac, Linux & theoretically Android too). This is because the Dart in its core still doesn't support Windows's AF_UNIX (windows implementation of unix socket) so the library is kind of language limited currently. But IPC socket connections can also be established using Windows NamedPipes (using win32 package) but I'm really new to Windows APIs & have no idea how to do so

**Comment by ryanheise** [comment]
I see, in that case I think it will be necessary to fix this in the just_audio_mpv plugin:

```yaml
  plugin:
    implements: just_audio_platform_interface
    platforms:
      linux:
        dartPluginClass: JustAudioMpv
        fileName: just_audio_mpv.dart
      windows:
        dartPluginClass: JustAudioMpv
        fileName: just_audio_mpv.dart
```

The windows declaration above can be deleted and perhaps re-added if mpv_dart some day adds support via win32.

Then what I can do for now is update the just_audio example so that it depends on both just_audio_mpv and just_audio windows, where each one declares support for a separate platform.

Right now, I'm not sure if there is a way for an app to selectively use just_audio_mpv for Linux and just_audio_windows for Windows, since then there are two plugins both declaring that they provide the Windows implementation. I don't know, maybe whichever one's declared second ends up overriding the first. There should probably be a feature request to the Flutter team to provide explicit options to select the plugin that's capable of supporting multiple platforms only for a specific platform.

**Comment by bleonard252** [comment]
The claim of Windows support has been removed. also the latest push to Pub now includes (frankly untested) fedora instructions since I forgot to with 0.1.2 earlier

**Comment by Pato05** [comment]
About this, I noticed @alexmercerind created `package:media_kit` a cross-platform player that internally uses libmpv via `dart:ffi`, so since `just_audio_mpv` wasn't really working out for my purposes, I created a new plugin [`just_audio_media_kit`](https://github.com/Pato05/just_audio_media_kit) which integrates `media_kit` to support both Linux and Windows.

I haven't currently tested on Windows, but since I'm not doing platform-specific stuff I'm guessing it'd work.

**Comment by alexmercerind** [comment]
> I created a new plugin [just_audio_media_kit](https://github.com/Pato05/just_audio_media_kit) which integrates media_kit to support both Linux and Windows.

[package:media_kit](https://github.com/media-kit/media-kit) offers both video & audio playback on all platforms. You [can efficiently select native libraries for minimal bundle size](https://github.com/media-kit/media-kit/tree/main#installation). The stability, performance & codec-support is solid (there are many unit-tests). Since it uses FFI, the feature implemented for one platform automatically works on all platforms (only video rendering is platform specific); and there's a lot that libmpv offers.

A good idea may be to [let dependents select media_kit_libs_***](https://github.com/Pato05/just_audio_media_kit/blob/main/pubspec.yaml#L16-L18) instead. There's no hard dependency on native libraries. Similar to package:just_audio_media_kit, project provides [package:video_player_media_kit](https://github.com/media-kit/media-kit/tree/main/video_player_media_kit) for zero-cost implementation / migration to package:video_player users.

**Comment by ryanheise** [comment]
Nice, @Pato05 (and @alexmercerind )!

Regarding request headers support, as you may or may not know, this is currently handled on the Dart side through just_audio's proxy, but I am currently working on changing this so that if the platform is able to support headers directly, the proxy won't be used. So the current code you have to pass through the headers will currently get overridden by the proxy, although in the upcoming change it will be exposed.

@alexmercerind , would you happen to know if mpv has any API that would facilitate playing clips? For example, the ability for playback to automatically stop at a precise timestamp?

**Comment by Pato05** [comment]
> A good idea may be to [let dependents select media_kit_libs_***](https://github.com/Pato05/just_audio_media_kit/blob/main/pubspec.yaml#L16-L18) instead. There's no hard dependency on native libraries.

That makes sense... I've put the hard dependencies because there wouldn't be any reason to use the plugin other than to also support Linux and Windows since `just_audio` already has its own implementation for all the other platforms.

By the way, great package!

**Comment by Pato05** [comment]
> Regarding request headers support, as you may or may not know, this is currently handled on the Dart side through just_audio's proxy, but I am currently working on changing this so that if the platform is able to support headers directly, the proxy won't be used. So the current code you have to pass through the headers will currently get overridden by the proxy, although in the upcoming change it will be exposed.

Oh, I didn't notice that while looking at `just_audio`'s code. I tried to implement every field that the `*Request()` object.

**Comment by UnicornsOnLSD** [comment]
> there wouldn't be any reason to use the plugin other than to also support Linux and Windows

I'd personally be interested in using `just_audio_media_kit` on Android/iOS to get around codec limitations (e.g., ALAC on Android and OGG/OPUS on iOS)

**Comment by ryanheise** [comment]
@jmshrv Beware that the native library is licensed under GPL which is feasible for distribution of open source apps on the desktop, but incompatible with the Play Store an App Store even if those apps are open source.

**Comment by alexmercerind** [comment]
@ryanheise 

> Would you happen to know if libmpv has any API that would facilitate playing clips? For example, the ability for playback to automatically stop at a precise timestamp?

Yes, there is. However not exposed in the package's API. We do provide an API to tinker with internal libmpv properties. There's a lot that libmpv offers & it's very easy to implement & test with FFI.

Refer to --start & --end: https://mpv.io/manual/stable/

> Beware that the native library is licensed under GPL.

package:media_kit is fully compatible with commercial usage. We compile our own builds for reduced bundle size & LGPL compatibility, [you can find relevant repositories here](https://github.com/media-kit).

**Comment by ryanheise** [comment]
Thanks for the insight into mpv's capabilities, it's good to know that clipping is theoretically possible.

I wasn't aware the native lib was LGPL rather than GPL although unfortunately even the LGPL is incompatible with the play store and app store, because it requires giving users the freedom to be able to re-link your app to a different version of the LGPL library and then run it which is not really feasible in a locked down system that users get through the app stores. This issue also affects ffmpeg. There is no issue with desktop apps, though.

**Comment by Pato05** [comment]
> I'd personally be interested in using `just_audio_media_kit` on Android/iOS to get around codec limitations (e.g., ALAC on Android and OGG/OPUS on iOS)

That would still be possible by manually calling the `JustAudioMediaKit.registerWith()` method and adding the required `media_kit` library dependencies.

**Comment by alexmercerind** [comment]
> I wasn't aware the native lib was LGPL rather than GPL although unfortunately even the LGPL is incompatible with the play store and app store, because it requires giving users the freedom to be able to re-link your app to a different version of the LGPL library and then run it which is not really feasible in a locked down system that users get through the app stores. This issue also affects ffmpeg. There is no issue with desktop apps, though.

**I don't happen to be a lawyer.**

Both (lib)mpv & (lib)VLC used to be only GPL. The re-licensing has been largely motivated with the aim to allow their usage in proprietary/commercial applications:

https://github.com/mpv-player/mpv/issues/2033
https://www.videolan.org/press/lgpl-libvlc.html

There are many applications that are distributed on Google Play or AppStore, which include dynamically-linked LGPL dependencies (even libmpv or FFmpeg).

If someone _* really *_ wishes to replace the native libraries bundled in an APK etc., I believe that is also possible with some repackaging. Regardless, one can't really do anything if operating system itself restricts users' actions.

Linking dynamically as a .dll (Windows)/ .so (Android, GNU/Linux)/ .dylib (macOS & iOS) is enough to comply with LGPL.

It's more like the code-push situation e.g.
- https://docs.shorebird.dev/faq#does-shorebird-comply-with-play-store-guidelines
- https://docs.shorebird.dev/faq#does-shorebird-comply-with-app-store-guidelines

<hr>

I'm unsubscribing to this thread, so I won't be receiving any notifications. It's getting bit noisy for me.

**Comment by maks** [comment]
I don't happen to be a lawyer either.

>Regardless, one can't really do anything if operating system itself restricts users' actions.

The problem @ryanheise is referring to is nothing to do with the OS *but* the policies, app developer licenses and terms of service of the App Store and Google Play. Those are legal agreements between an app developer, users and Apple/Google, just because they restrict their users freedoms, hence the long standing issue with distributing GPL'd software via the App store. 

@alexmercerind App store users and app developers are not allowed to comply with the provisions of the GPL hence its not up to you to say "if they really wished to". 

I also have no idea why you referenced shorebird, that is a specifically different set of provisions of the Apple Developer Program License Agreement (section 3.2.2) that they are referring to due to its prohibition on executing downloaded code and really has nothing to do with the issue at hand here.

**Comment by alexmercerind** [comment]
@maks 

**I don't happen to be a lawyer.**

>  The policies, app developer licenses and terms of service of the App Store and Google Play. Those are legal agreements between an app developer, users and Apple/Google, just because they restrict their users freedoms, hence the long standing issue with distributing GPL'd software via the App store.

- Source?
- GPL & LGPL is different.

> App store users and app developers are not allowed to comply with the provisions of the GPL hence its not up to you to say "if they really wished to".

I don't understand on what basis (without source), you say:
"app developers are not allowed to comply with the provisions of the GPL". 

According to LGPL (to my understanding), the end-users must have an option to replace/update the linked LGPL code. The closest that one can get (is expected & followed) to allowing this on any platform (not just Android & iOS) is linking the LGPL code dynamically. If users _* really *_ wish to dive in & replace the default LGPL shared libraries, they can (& there are methods that allow, of-course not "official" by Google Play or AppStore).

It must be kept in mind that Google Play or AppStore are just a way to distribute applications. You could even argue that using dynamically linked LGPL libraries in an application distributed on Microsoft Store is not legal since it bundles the application differently.

> I also have no idea why you referenced shorebird, that is a specifically different set of provisions of the Apple Developer Program License Agreement (section 3.2.2) that they are referring to due to its prohibition on executing downloaded code and really has nothing to do with the issue at hand here.

I referenced it at the end of my comment, because it has a similar situation & no clear answer. The legal process is entirely different. At many times, it has been seen that things boil down to how good your legal team or lawyer is.

From what I've known & told so far, it is fine. I don't have time to closely read every license & agreement to convince anyone in support/against based on any clause or section that I find.

<hr>

Like I said in my comment earlier, **there are thousands of applications available on Google Play & AppStore which include dynamically-linked LGPL dependencies in form of shared libraries.** Both libmpv & libVLC were re-licensed with primary aim of allowing their usage in commercial/proprietary applications, I don't think it offends them.

You can [read the linked mpv issue to understand their motivation](https://github.com/mpv-player/mpv/issues/2033) & why exactly LGPL (& not MIT, Apache-2.0 etc.). FYI: any improvements that are made to the package are still open-source (either to package or mpv directly).

<hr>

You are free to make your own decisions & hold accountability.

Use package:media_kit or don't. We had this discussion a lot time ago internally while starting to work on project.

**Comment by maks** [comment]
@alexmercerind and as I said, I don't happen to be a lawyer either.

>I referenced it at the end of my comment, because it has a similar situation & no clear answer.
That is not the case, Shorebird have outlined clearly the technical means they have implemented to specifically not be in contravention of the relevant clause of the Apple Developer Program License Agreement. In regards to use of the LGPL in apps deployed via the App store that is not the case as users are specifically prohibited from modifying the apps that they obtain from the app store, hence may not relink the dynamically linked libraries

> of-course not "official" by Google Play or AppStore).

it's nothing to do with using loose language like not being "official", its not some sort of grey area, its about breaking the terms of service of the stores. 

>You are free to make your own decisions & hold accountability.

Exactly, that I 100% agree with you on, as a developer doing due diligence for development of apps for a commercial client for  to be deployed via App Store or Google play, I can easily recommend the use of libraries under an MIT or BSD license, I could not do so for LGPL licenses ones, the choices you make are of course up to you.

**Comment by ryanheise** [comment]
(IANAL)

> Like I said in my comment earlier, there are thousands of applications available on Google Play & AppStore which include dynamically-linked LGPL dependencies in form of shared libraries.

Indeed there are many apps on the app stores that are not compliant with open source licenses. A [2011 study](https://techcrunch.com/2011/03/08/potential-open-source-license-violations-in-android-and-ios-apps/) found 71% of apps using open source libraries to be non-compliant with their licenses. A more recent [2017 study](https://dl.acm.org/doi/10.1145/3133956.3134048) found a much smaller percent although still 40K apps. The fact that many people do it doesn't itself make it legal, so it would probably be best advised for each app developer to consult their own lawyer.

One more interesting link: [Google themselves](https://source.android.com/docs/setup/about/licenses) warn about using LGPL on Android, stating:

> * In simplified terms, LGPL requires shipping of source to the application; a written offer for source; or linking the LGPL-ed library dynamically and allowing users to manually upgrade or replace the library. Android software is typically shipped as a static system image, so complying with these requirements restricts device manufacturer designs. For instance, it's difficult for a user to replace a library on read-only flash storage.
> * LGPL requires the allowance of customer modification and reverse engineering for debugging those modifications. Most device makers don't want to be bound by these terms.
> * Historically, LGPL libraries have been the source of many compliance problems for downstream device makers and application developers. Educating engineers on these issues is difficult and time consuming. It's critical to Android's success that device makers can easily comply with the licenses.

For further reading, [here](https://stackoverflow.com/a/9070734/13949389) is a StackOverflow post that gives a fairly decent summary of the issues. There was also an ffmpeg thread I can't find right now where the issue was discussed, and even if the authors would agree in principle apps "should" be allowed to use the software on iOS/Android, or at least that usage is in the spirit of what they might have originally intended (before the app stores came about), now that the app stores are here and there is this license incompatibility, it was basically concluded that ffmpeg has so many different authors over so many years that it would be next to impossible to get everybody's agreement to change the license to something that would be compatible with the app stores. Now, it may technically be possible in some situations to provide instructions to the user on how to re-link your app and rebuild it and then install it, perhaps more feasible on Android than iOS, and a few years ago I went down that path trying of trying to be fully compliant by doing this, but in the end I gave up. @alexmercerind you are completely right that the software can still exist, and it is simply up to the app developer whether to use it or not, after coming to their own legal determination (ideally in consultation with a lawyer, of course).

**Comment by alexmercerind** [comment]
> I can easily recommend the use of libraries under an MIT or BSD license, I could not do so for LGPL licenses ones, the choices you make are of course up to you.

Informally speaking, I draw my line at GPL ;)

<hr>

Thanks for sharing some interesting metrics @ ryanheise. I have shared the mpv thread regarding their LGPL re-license. I personally believe that "the spirit of what they might have originally intended" is preserved.

<hr>

My legal talk quota is reached for this month. 😄

**Comment by Pato05** [comment]
That was.. an interesting discussion to say the least. On the other hand, are there any concerns with distributing app bundles on desktop? I know that the linux version requires mpv installed on the system to work. I wonder whether it's the same on Windows though.

About Android, shouldn't mpv-android on the Play Store have the same issue? It seems to based on libmpv, just like media_kit

**Comment by alexmercerind** [comment]
@Pato05 

> About Android, shouldn't mpv-android on the Play Store have the same issue? It seems to based on libmpv, just like media_kit

I've said it before & I'll say it again there is no issue.

There are thousands applications (big & small) available on AppStore & Google Play that use dynamically-linked LGPL dependencies. For instance, there's [ijkplayer](https://github.com/bilibili/ijkplayer#commercial-use), specifically for Android & iOS from Bilibili, which is LGPL.

Just link dynamically to external LGPL code & you're good. You aren't offending anyone.

"Re-linking" is often as simple as deleting old file & adding new one.

> I know that the linux version requires mpv installed on the system to work. I wonder whether it's the same on Windows though.

That's how GNU/Linux works. If you see closely, you'll see we don't provide own libmpv builds for GNU/Linux. On other platforms, there is zero configuration required outside of adding packages to your pubspec.yaml.

I have provided direct download links to demo applications in the README for each platform for you to evalulate.

**Comment by ryanheise** [comment]
> About Android, shouldn't mpv-android on the Play Store have the same issue? It seems to based on libmpv, just like media_kit

In the case of mpv-android, it is an open source app, and so it would seem to trivially satisfy Clause 6a of the LGPL. In a closed source app, the case on Desktop is also quite trivial by Clause 6b since you dynamically linked libraries to allow the library to be stored in a separate file and you could then easily just replace the file without rebuilding the app. On Android, a user with a typical Android phone won't be able to do that, so you would need to provide them with a way to rebuild your app with the alternative library based on your object code rather than your source code. There are some cases in which this is possible, and some cases in which this is not possible. But in cases where it is possible, it is still a rather complicated process. You should at least demonstrate that it is possible, and then provide your users with a way to do that.

In my opinion, it's a rather impractical clause in the context of mobile apps, and if I were in your shoes, I would first try to fully comply with the license, then if that proved too difficult, I would then try to either persuade the authors to remove the problematic clause from the license, or try a substitute with a more acceptable license.
