### ISSUE TITLE
Pods issue on macOS Monterey 12.0.1

### ISSUE THREAD

**Issue by jonny7737** [ryanheise/just_audio#572]
**Which API doesn't behave as documented, and how does it misbehave?**
Not an API issue.  build of package example fails.

**Minimal reproduction project**
The example

**To Reproduce (i.e. user steps, not code)**
1. From project directory
2. flutter run
3. build fails

**Error messages**

```
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
      because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "just_audio":
      In Podfile:
        just_audio (from `Flutter/ephemeral/.symlinks/plugins/just_audio/macos`)

    Specs satisfying the `just_audio (from
    `Flutter/ephemeral/.symlinks/plugins/just_audio/macos`)` dependency were
    found, but they required a higher minimum deployment target.
```

**Expected behavior**
Expected example app to run.

**Screenshots**
No screens => no screenshots.

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 - None - Desktop application

**Smartphone (please complete the following information):**
 - Device:N/A
 - OS: N/A

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] VS Code (version 1.53.0-insider)
[✓] Connected device (2 available)

• No issues found!
```

**Additional context**
I would very much like to try this audio player.

**Comment by ryanheise** [comment]
Hi @jonny7737 any update on this?

**Comment by ryanheise** [comment]
I see, have you tried the official example and does it contain the bug you reported?

**Comment by jonny7737** [comment]
Official example has the same issue:

ld: warning: dylib (/Users/jonny/Downloads/just_audio-master/just_audio/example/build/macos/Build/Products/Debug/just_audio/just_audio.framework/just_audio) was built for newer macOS version (10.12.2) than being linked (10.11)

And the build runs as expected.

**Comment by FaKenKoala** [comment]
Below solution is working for me:

1.  comment the `platform :osx, '10.11'` in macos/Podfile
2. delete Podfile.lock and run pod install:
`cd macos && rm Podfile.lock && pod install`

**Comment by yy1300326388** [comment]
`macos/Podfile` replace ` platform :osx, '10.11'` to `platform :osx, '10.15'`

**Comment by meng-fucius** [comment]
> `macos/Podfile` replace ` platform :osx, '10.11'` to `platform :osx, '10.15'`

this worked for me

**Comment by ryanheise** [comment]
Hmm, the official example already has `platform :osx, '10.15'`, but it has been reported by @jonny7737 that this official example still doesn't work:

> Official example has the same result as reported in my second post:
> 
> ld: warning: dylib (/Users/jonny/Downloads/just_audio-master/just_audio/example/build/macos/Build/Products/Debug/just_audio/just_audio.framework/just_audio) was built for newer macOS version (10.12.2) than being linked (10.11)
> 
> And the build runs as expected.

**Comment by ryanheise** [comment]
May I ask what version of Xcode you're using?

**Comment by Ruzo** [comment]
> May I ask what version of Xcode you're using?

Hi, it's Xcode version 13.2.1 (13C100)

**Comment by ryanheise** [comment]
I may need to test that version of Xcode in order to reproduce this.

**Comment by Ruzo** [comment]
Great! Thank you for looking into it.

**Comment by ryanheise** [comment]
However, I can't say it's easy/quick, I'm short on storage space and the whole installation process usually requires me to do a painful game of musical chairs to make enough space to perform the installation.

**Comment by Ruzo** [comment]
Alright, I did a search in the code to see where it was `being linked (10.11)` and found `10.11` as value for the `MACOSX_DEPLOYMENT_TARGET` in the `project.pbxproj` file in `macos/Runner.xcodeproj/` folder.  I changed it to `10.12.2` in all three spots where it was assigned the `10.11` version. 

There are no warnings anymore. I don't know if there will be a nasty surprise waiting for me in some later process.

**Comment by Ruzo** [comment]
> @Ruzo would you consider making a pull request for that change? If you can verify that it works in your newer version of Xcode and I can verify that it works in my older version of Xcode, then I'll merge and publish it. (Although after that, I will definitely want to upgrade Xcode because Flutter 3 requires it.

I made these changes in my own project's `macos` folder so `MACOSX_DEPLOYMENT_TARGET` is only present in your `example` folder.

The only code that references `10.11` is in the `UriAudioSource.m` file in `darwin/Classes/` and `ios/Classes/` folders. It seems to be checking for macOS version availability. What would be the best way to fix it?

**Comment by ryanheise** [comment]
> I made these changes in my own project's `macos` folder so `MACOSX_DEPLOYMENT_TARGET` is only present in your `example` folder.

Here my interest is in making sure the official example is fixed. Does the unmodified official example work for you as is?

**Comment by Ruzo** [comment]
These are the warnings I get with the example:
```
/Users/richardrouzeau/.pub-cache/hosted/pub.dartlang.org/audio_session-0.1.6+1/macos/Classes/AudioSessionPlugin.m:14:5: warning: expression result unused [-Wunused-value]
    [[AudioSessionPlugin alloc] initWithRegistrar:registrar];
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
ld: warning: dylib (/Users/richardrouzeau/apps/Flutter/just_audio/just_audio/example/build/macos/Build/Products/Debug/just_audio/just_audio.framework/just_audio) was built for newer macOS version (10.12.2) than being linked (10.11)
: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
lib/main.dart:27
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../../flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance?.addObserver(this);
                   ^
: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
lib/main.dart:55
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../../flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1

    WidgetsBinding.instance?.removeObserver(this);
```

I also found that you have `s.platform = :osx, '10.12.2'` in the package's `/macos/just_audio.podspec` folder.

**Comment by ryanheise** [comment]
That could be it... If you bump up that version, does it fix the warning?

**Comment by Ruzo** [comment]
Fixing the `WidgetsBinding` warning eliminates all other warnings except for the macOS version one. I tried bringing the `s.platform` version up and down but it's not making a difference. Would it be because it's cached?

**Comment by ryanheise** [comment]
The WidgetsBinding warning is separate from this issue, and I will commit a fix for that separately.

Perhaps you are right about the cache. Can you try doing a `flutter clean` and possibly removing the Pods dir?

**Comment by Ruzo** [comment]
I finally got to test it with different versions. Bringing the version down to `10.11` is actually what works.

So setting `s.platform = :osx, '10.11'` in the `/just_audio/macos/just_audio.podspec` file eliminates the versions warning.

**Comment by ryanheise** [comment]
Interesting, although from memory the macOS implementation uses some APIs that require a higher version...

**Comment by ryanheise** [comment]
So confirming with the Apple documentation, certain parts of the code do indeed require macOS 10.12, so I don't think lowering the it to 10.11 will be a correct solution.

**Comment by ryanheise** [comment]
That comes from the Apple API documentation's stated availability. However, I suppose since the plugin's podspec targets 10.12.2 or later, it may be a matter of simply editing `UriAudioSource.m` so that it uses a version number that is at least the number from the API documentation, but also at least the number from the plugin's podspec.

**Comment by Ruzo** [comment]
Editing the `UriAudioSource.m` does not make a difference. It seems like having `s.platform = :osx, '10.12.2'` in the `/just_audio/macos/just_audio.podspec` file requires a project to also have its `MACOSX_DEPLOYMENT_TARGET` set to '10.12.2'.

**Comment by ryanheise** [comment]
I have finally managed to upgrade Xcode and I can confirm the issue does now happen for me. I'll take some time to investigate.

**Comment by ryanheise** [comment]
After some Googling, it turns out that this is just a result of not completely upgrading the build tools when upgrading Xcode. Here is how I got it working for me:

```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
sudo gem install cocoapods
flutter clean
```

After doing all of that, it now builds and runs successfully. There are still the same warnings, but after these steps, they are no longer fatal.

**Comment by ryanheise** [comment]
I've just committed fixes for the various warnings on the `fix/flutter3` branch. Please let me know whether it works for you, in addition to trying the upgrade instructions in https://github.com/ryanheise/just_audio/issues/572#issuecomment-1139728529

**Comment by Ruzo** [comment]
The warnings were never "fatal" in my case.

With the `fix/flutter3` branch and `MACOSX_DEPLOYMENT_TARGET` still set to `10.12.2`, There is only the `AudioSessionPlugin` warning left.

```
/Users/richardrouzeau/.pub-cache/hosted/pub.dartlang.org/audio_session-0.1.7/macos/Classes/AudioSessionPlugin.m:14:5: warning: expression result unused [-Wunused-value]
    [[AudioSessionPlugin alloc] initWithRegistrar:registrar];
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
This warning only shows up on the first run after `just_audio` has been freshly installed. Like after `flutter clean`.

**Comment by ryanheise** [comment]
Yes I still have to fix the audio_session warning, although it's for a separate plugin so I'll need to address it over on that project.

Regarding just_audio, did your fatal error go away with just the `fix/flutter3` branch, or did you also need to do the `xcode-select` thing?

**Comment by ryanheise** [comment]
The `fix/flutter3` branch has now been published to just_audio 0.9.22, so I'll close this issue. I'll monitor whether people still run into build errors and if so consider adding instructions to the README on how to upgrade Xcode.

**Comment by Ruzo** [comment]
> Yes I still have to fix the audio_session warning, although it's for a separate plugin so I'll need to address it over on that project.
> 
> Regarding just_audio, did your fatal error go away with just the `fix/flutter3` branch, or did you also need to do the `xcode-select` thing?

Doing the `xcode-select` thing and using the `fix/flutter3` branch does not fix the non-fatal version warning in my case. I still have to bump up the `MACOSX_DEPLOYMENT_TARGET` value which seems to be normal behavior for the support of certain features of just_audio.

**Comment by ryanheise** [comment]
OK, it sounds you already had most of the pieces of the puzzle already in place. Hopefully the above discussion will help people who stumble across the same error.
